* org-to-markdown example

A simple org-to-markdown example

** Usage 

Run it with node:

#+begin_src sh
$ node index.js
#+end_src

* Math

You can embed LaTeX math formatting in Org mode files.

** Inline math expressions

For *inline math* expressions, use the parentheses notation ~\(...\)~:

#+begin_src org
The formula \(a^2 + b^2 = c^2\) has been discovered by Pythagoras.

Let \(a=\sin(x) + \cos(x)\). Then \(a^2 = 2\sin(x)\cos(x)\) because \(\sin^2x +
\cos^2x = 1\).
#+end_src

#+begin_warning
It's /not/ advised to use the ~$...$~ construct (both for Org and for MathJax).

Don't forget that ~$~ is also a valid currency symbol!
#+end_warning

** Math expressions in display mode

For mathematical expressions which you want to make *stand out, centered on their
own lines*, use ~\[...\]~:

#+begin_src org
The /Euler theorem/:

\[
\int_0^\infty e^{-x^2} dx = {{\sqrt{\pi}} \over {2}}
\]

LaTeX allows to inline such ~\[...\]~ constructs (/quadratic formula/):
\[ \frac{-b \pm \sqrt{b^2 - 4 a c}}{2a} \]
#+end_src

#+begin_warning
Double dollar signs (~$$~) should not be used.
#+end_warning

#+begin_src org
\[
\left( \int_{0}^{\infty} \frac{\sin x}{\sqrt x}\,\mathrm{d}x \
right)^{2} -
\prod_{k=1}^{\infty} \frac{4k^{2}}{4k^{2}-1} +
\frac{\lambda}{2n}\sum_{k=1} ^{n} \theta_{k} ^{2} x^{n} = 0
\]
#+end_src

The equation may be wrong, but it's a nice one!

** Equation numbers

Differently from ~$...$~ and ~\(...\)~, an equation environment produces a *numbered*
equation to which you can add a label and reference the equation by (label) name
in other parts of the text. This is not possibly with unnumbered math
environments (~$$~, ...).

#+begin_src org
The /Pythagoras theorem/:

,#+name: pythag
\begin{equation}
a^2 + b^2 = c^2
\end{equation}

See equation [[pythag]].

# The /sinus theorem/ can be written as the equation:
#
# \begin{equation}
# \label{eqn:sinalpha}
# \frac{\sin\alpha}{a}=\frac{\sin\beta}{b}
# \end{equation}
#
# See equation [[eqn:sinalpha]].
#+end_src

Only captioned equations are numbered.

Other alternatives: use
- ~\begin{equation*}~ or
- ~\begin{displaymath}~ (= the verbose form of the ~\[...\]~ construct).

~M-q~ does not fill those.

* Miscellaneous effects

** Include Org files

You can include another Org file and skip its title by using the ~:lines~ argument
to ~#+INCLUDE~:

#+begin_src org
,#+INCLUDE: "chapter1.org" :lines "2-"
#+end_src

#+begin_note
File inclusion, through INCLUDE keywords, is an *export-only feature*.
#+end_note

The source code blocks support syntax highlighting:

#+begin_src cpp :eval no
/*
 * Application that displays a "Hello" message to the standard output.
 */
int main(int arc, char **argv)
{
  printf("Hello, %s!\n", (argc>1) ? argv[1] : "World");
  return 0;
}
#+end_src

#+begin_src emacs-lisp :eval no
(defvar hello "Hello")

(defun hello (name &optional greeting)
  (message "%s %s" (or greeting "Hello") name))

(setq tab-width 4)
#+end_src

